# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-tmscli-pull-po

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true
      CHECKOUT:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      LANGUAGE:
        type: string
        required: true
      MODE_OF_UPDATE:
        type: string
        required: true
      CALLER_JOB:
        type: string
        required: true
      ENABLE_JOB:
        type: boolean
        required: true
      ACTOR_ID:
        type: string
        required: true
      ACTOR_NAME:
        type: string
        required: true
      ACTOR_LOGIN:
        type: string
        required: true
    secrets:
      ACTOR_GITHUB_TOKEN:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true

jobs:
  tmscli-pull-po:
    if: ${{ inputs.ENABLE_JOB }}
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Print Contexts/Inputs/Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
          echo "inputs.MODE_OF_UPDATE = ${{ inputs.MODE_OF_UPDATE }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "inputs.ACTOR_ID = ${{ inputs.ACTOR_ID }}"
          echo "inputs.ACTOR_NAME = ${{ inputs.ACTOR_NAME }}"
          echo "inputs.ACTOR_LOGIN = ${{ inputs.ACTOR_LOGIN }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"
          echo "secrets.CROWDIN_PERSONAL_TOKEN = ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Get Other Caches from versions.json
        id: gocv
        uses: ./.github/actions/get-other-caches-from-versions-file
        with:
          version: ${{ inputs.VERSION }}
          versions-file: 'versions.json'

      - name: Install CMake
        uses: ./.github/actions/install-cmake

      - name: Install Gettext
        uses: ./.github/actions/install-gettext

      - name: Install Crowdin
        uses: ./.github/actions/install-crowdin

      - name: Configure the '${{ inputs.LANGUAGE }}' preset for '${{ inputs.VERSION }}' version
        uses: ./.github/actions/cmake-configure-preset
        with:
          source-directory: ${{ github.workspace }}
          preset: ${{ inputs.LANGUAGE }}
          cache-version: ${{ inputs.VERSION }}
          cache-mode-of-update: ${{ inputs.MODE_OF_UPDATE }}
          cache-auto-depend: 'OFF'
          cache-version-compendium: ${{ steps.gocv.outputs.VERSION_COMPENDIUM }}
          cache-version-of-python: ${{ steps.gocv.outputs.VERSION_OF_PYTHON }}
          cache-version-of-sphinx: ${{ steps.gocv.outputs.VERSION_OF_SPHINX }}
          cache-version-of-doxygen: ${{ steps.gocv.outputs.VERSION_OF_DOXYGEN }}
          cache-version-of-proj: ${{ steps.gocv.outputs.VERSION_OF_PROJ }}

      - name: Build the 'gettext_update_po' target
        uses: ./.github/actions/cmake-build-target
        with:
          source-directory: ${{ github.workspace }}
          preset: ${{ inputs.LANGUAGE }}
          target: 'gettext_update_po'

      - name: Build the 'tmscli_pull_po' target
        uses: ./.github/actions/cmake-build-target
        with:
          source-directory: ${{ github.workspace }}
          preset: ${{ inputs.LANGUAGE }}
          target: 'tmscli_pull_po'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Get the Crowdin Status Progress of the '${{ inputs.VERSION }}' branch
        id: gtpp
        uses: ./.github/actions/get-crowdin-status-progress
        with:
          crowdin-config-file: 'l10n/${{ inputs.VERSION }}/crowdin.yml'
          crowdin-branch-name: ${{ inputs.VERSION }}
          crowdin-personal-token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          crowdin-no-progress: true
          crowdin-verbose: true

      - name: Build the 'gettext_statistic_po' target
        uses: ./.github/actions/cmake-build-target
        with:
          source-directory: ${{ github.workspace }}
          preset: ${{ inputs.LANGUAGE }}
          target: 'gettext_statistic_po'

      - name: Get the Current Job's ID
        id: gcji
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          job_name: '${{ inputs.CALLER_JOB }} / ${{ github.job }}'
          per_page: 100

      - name: Set up mutex for 'l10n' branch
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: mutex/l10n
          repo-token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

      - name: Add and Commit Changes
        id: acc
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './l10n'
          add: './${{ inputs.VERSION }}'
          pull: '--rebase --autostash'  # required 'actions/checkout' with 'fetch-depth: 0'
          author_name: ${{ inputs.ACTOR_NAME }}
          author_email: ${{ inputs.ACTOR_ID }}+${{ inputs.ACTOR_LOGIN }}@users.noreply.github.com
          message: |
            tr(${{ inputs.VERSION }}): pull ${{ inputs.LANGUAGE }} translations from Crowdin

            ${{ steps.gtpp.outputs.CROWDIN_STATUS_PROGRESS }}

            Created by GitHub Workflows:

            - File: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.gcji.outputs.job_id }}

      - name: Check Outputs of the Commit
        if: ${{ steps.acc.outputs.committed == 'true' }}
        shell: bash
        run: |
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
